export const REVIEW_TCP_CLIENT = Symbol('REVIEW_TCP_CLIENT');
export const REVIEW_RPC_GATEWAY = Symbol('REVIEW_RPC_GATEWAY');
export const REVIEW_SESSION_AUTHENTICATOR = Symbol(
  'REVIEW_SESSION_AUTHENTICATOR',
);
