# syntax=docker/dockerfile:1.7
FROM node:24-alpine

RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm@11.1.2

ENV CI=true

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/web/package.json apps/web/package.json
COPY apps/admin/package.json apps/admin/package.json

RUN --mount=type=cache,id=uitfoodms-frontend-pnpm-store,target=/pnpm/store \
    pnpm config set store-dir /pnpm/store && \
    pnpm --filter web \
      --filter admin \
      install --frozen-lockfile --config.confirmModulesPurge=false --config.package-import-method=copy

COPY apps/web/index.html apps/web/vite.config.ts apps/web/tsconfig.json apps/web/tsconfig.app.json apps/web/tsconfig.node.json apps/web/components.json apps/web/eslint.config.js apps/web/
COPY apps/web/public apps/web/public
COPY apps/web/src apps/web/src

COPY apps/admin/index.html apps/admin/vite.config.ts apps/admin/tsconfig.json apps/admin/tsconfig.app.json apps/admin/tsconfig.node.json apps/admin/components.json apps/admin/eslint.config.js apps/admin/
COPY apps/admin/public apps/admin/public
COPY apps/admin/src apps/admin/src

EXPOSE 5173 5174
