export const ORDERING_RPC_GATEWAY = Symbol('ORDERING_RPC_GATEWAY');
export const ORDERING_TCP_CLIENT = Symbol('ORDERING_TCP_CLIENT');
export const ORDERING_SESSION_AUTHENTICATOR = Symbol(
  'ORDERING_SESSION_AUTHENTICATOR',
);
