FROM node:22-alpine
RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm@11.1.2
ENV CI=true
WORKDIR /app
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json turbo.json ./
COPY apps/services/payment/package.json apps/services/payment/package.json
COPY packages/contracts/package.json packages/contracts/package.json
RUN pnpm install --frozen-lockfile --config.confirmModulesPurge=false
COPY . .
WORKDIR /app/apps/services/payment
CMD ["pnpm", "run", "dev"]
