import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as schema from '../../auth/auth.schema';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});
export const db = drizzle(pool, { schema });

import 'dotenv/config';
import { hashPassword } from 'better-auth/crypto';

/**
 * Restaurant owner identity accounts.
 *
 * The catalog service's restaurant seeds (nearby-vnu-nutrition,
 * vegan-nutrition, beverage-restaurants, food-and-beverage-restaurants)
 * reference these ids as `restaurants.ownerId`, but a restaurant owner can
 * only log in once a matching `user`/`account` row exists in the identity
 * service's own database. Ids below must stay in sync with the `id` /
 * `accountId` values generated by each of those catalog seed files.
 */
const restaurantOwners = [
  // nearby-vnu-nutrition.seed.ts
  {
    id: '56000001-0000-4000-8000-000000000001',
    accountId: '56000002-0000-4000-8000-000000000001',
    name: 'Fresh Bowl VNU Owner',
    email: 'fresh-bowl-vnu-owner@soli.dev',
    password: 'password1234',
  },
  {
    id: '56000001-0000-4000-8000-000000000002',
    accountId: '56000002-0000-4000-8000-000000000002',
    name: 'Grill Lab KTX Owner',
    email: 'grill-lab-ktx-owner@soli.dev',
    password: 'password1234',
  },
  {
    id: '56000001-0000-4000-8000-000000000003',
    accountId: '56000002-0000-4000-8000-000000000003',
    name: 'Morning Market Cafe Owner',
    email: 'morning-market-cafe-owner@soli.dev',
    password: 'password1234',
  },
  // vegan-nutrition.seed.ts
  {
    id: '59000001-0000-4000-8000-000000000001',
    accountId: '59000002-0000-4000-8000-000000000001',
    name: 'Green Leaf Vegan Owner',
    email: 'green-leaf-owner@soli.dev',
    password: 'password1234',
  },
  {
    id: '59000001-0000-4000-8000-000000000002',
    accountId: '59000002-0000-4000-8000-000000000002',
    name: 'Harmony Eats Owner',
    email: 'harmony-eats-owner@soli.dev',
    password: 'password1234',
  },
  // beverage-restaurants.seed.ts
  {
    id: '57000001-0000-4000-8000-000000000001',
    accountId: '57000002-0000-4000-8000-000000000001',
    name: 'VNU Coffee Owner',
    email: 'vnu-coffee-owner@soli.dev',
    password: 'password1234',
  },
  {
    id: '57000001-0000-4000-8000-000000000002',
    accountId: '57000002-0000-4000-8000-000000000002',
    name: 'Boba Corner Owner',
    email: 'boba-corner-owner@soli.dev',
    password: 'password1234',
  },
  // food-and-beverage-restaurants.seed.ts
  {
    id: '58000001-0000-4000-8000-000000000001',
    accountId: '58000002-0000-4000-8000-000000000001',
    name: 'Study Cafe Owner',
    email: 'study-cafe-owner@soli.dev',
    password: 'password1234',
  },
];

async function main() {
  console.log('Seeding restaurant owner identity accounts...');

  for (const owner of restaurantOwners) {
    await db
      .insert(schema.user)
      .values({
        id: owner.id,
        name: owner.name,
        email: owner.email,
        emailVerified: true,
        role: 'restaurant',
      })
      .onConflictDoUpdate({
        target: schema.user.id,
        set: {
          name: owner.name,
          email: owner.email,
          emailVerified: true,
          role: 'restaurant',
          updatedAt: new Date(),
        },
      });

    const passwordHash = await hashPassword(owner.password);

    await db
      .insert(schema.account)
      .values({
        id: owner.accountId,
        accountId: owner.id,
        providerId: 'credential',
        userId: owner.id,
        password: passwordHash,
      })
      .onConflictDoUpdate({
        target: schema.account.id,
        set: {
          accountId: owner.id,
          providerId: 'credential',
          userId: owner.id,
          password: passwordHash,
          updatedAt: new Date(),
        },
      });
  }

  console.log(
    `Seeded ${restaurantOwners.length} restaurant owner identity accounts.`,
  );
  await pool.end();
  process.exit(0);
}

main().catch(async (error) => {
  console.error('Restaurant owner identity seed failed:', error);
  await pool.end();
  process.exit(1);
});
