FROM node:24-alpine
WORKDIR /app
RUN corepack enable
ENV CI=true
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/contracts/package.json packages/contracts/package.json
COPY apps/services/review/package.json apps/services/review/package.json
RUN pnpm install --frozen-lockfile --config.confirmModulesPurge=false
COPY packages/contracts packages/contracts
COPY apps/services/review apps/services/review
WORKDIR /app/apps/services/review
CMD ["pnpm", "dev"]
