export const CATALOG_RPC_GATEWAY = Symbol('CATALOG_RPC_GATEWAY');
export const CATALOG_TCP_CLIENT = Symbol('CATALOG_TCP_CLIENT');
export const CATALOG_SESSION_AUTHENTICATOR = Symbol(
  'CATALOG_SESSION_AUTHENTICATOR',
);
